- .github/workflows/ci.yml
- carnot/beaconized_carnot.py
- carnot/overlay.py
- carnot/test_beacon_verification.py
- carnot/test_beaconized_carnot.py
- carnot/test_happy_path.py
- carnot/test_tree_overlay.py
- carnot/test_unhappy_path.py
- carnot/tree_overlay.py
When importing packages that we wrote, use a prefix `carnot.`, so that we can run unit tests at the project root using `python -m unittest`.
This would be useful for other packages other than carnot to be added, such as `mixnet`.
> Use package prefix to run unittests at the root dir

- mixnet/__init__.py
- mixnet/bls.py
- mixnet/fisheryates.py
- mixnet/mixnet.py
- mixnet/test_fisheryates.py
- mixnet/test_mixnet.py
- mixnet/utils.py
- requirements.txt
This is the first PR of the series of Mixnet spec.
This PR represents:
- https://www.notion.so/Mixnet-Specification-807b624444a54a4b88afa1cc80e100c2#1e3a0deec22242d3a12cb54b65413049
- https://www.notion.so/Mixnet-Specification-807b624444a54a4b88afa1cc80e100c2?pvs=4#18b6e714554447d5a824aec1f1891403
> Mixnet: Add basic structure and topology construction

- .github/workflows/ci.yml
- requirements.txt
Closes #43 
Since Python 3.12, `setuptools` is not bundled, which is required to build `blspy`.
https://github.com/python/cpython/issues/95299
To resolve this, I added `setuptools` to the `requirements.txt`.
Also, I had to bump some packages to make it compile on Python 3.12.
> Use Python 3.12 and install setuptools

- mixnet/mixnet.py
- mixnet/node.py
- mixnet/poisson.py
- mixnet/test_node.py
- mixnet/test_packet.py
- requirements.txt
This PR covers the specification of packet delay in mix nodes: https://www.notion.so/Mixnet-Specification-807b624444a54a4b88afa1cc80e100c2?pvs=4#15ccbb03a44f42658ea67a33527ecea2.
In summary,
assuming that the packet receiving rate of a mix node follows a Poisson distribution $\lambda$, the mix node should be implementation to approximate a [M/M/∞ queue](https://en.wikipedia.org/wiki/M/M/%E2%88%9E_queue) with packet delays that follow an exponential distribution $\mu$. With this setup, the packet emission rate of a mix node must be $\lambda$, and the mean number of packets being processed by a mix node at any time must be $\lambda/\mu$. 
A unit test checks these properties.
> Mixnet: Packet delay in mix node

- cryptarchia/cryptarchia.py
- cryptarchia/test_fork_choice.py
Add the fork choice rule as described in 'Ouroboros Genesis: Composable Proof-of-Stake Blockchains with Dynamic Availability'
Tests still missing
> Add fork choice rule

- cryptarchia/cryptarchia.py
Please correct me if I'm wrong.
It seems that the `absolute_slot` needs to be calculated based on the `chain_start_time`, if I understand correctly. 
And, according the code here, it looks like the unit of the parameter `s` is "slots", not seconds. I added it in the comment. Did I get it correctly?
> Clarify Cryptarchia slot calcuation

- mixnet/client.py
- mixnet/mixnet.py
- mixnet/packet.py
- mixnet/robustness.py
- mixnet/test_client.py
- mixnet/test_mixnet.py
- mixnet/test_node.py
- mixnet/test_packet.py
- mixnet/test_robustness.py
This is a new PR replacing the previous PR #51 closed.
This PR describes a [deterministic topology update](https://www.notion.so/Mixnet-Specification-807b624444a54a4b88afa1cc80e100c2?pvs=4#af141ade3e8147ec900cf3599953f4da) by introducing a "robustness layer" between a consensus layer and a mixnet layer. For details of design rationales, please see the spec in Notion that I linked above.
> Mixnet: topology update

- cryptarchia/cryptarchia.py
- cryptarchia/test_leader.py
y is derived from "LEAD"||epoch_nonce||slot||coin_sk||coin_nonce
Also in this PR, standardize encoding to big-endian
> Leader VRF uses coin nonce as well as sk

- install-arkworksbls-arch64-osx.sh
pip installs the x64 precompiled version of the arks dependancy library. Not working on macos using mX chipsets. This helps dealing with that manually
> Arkworks dependency utility script

- da/kzg_rs/common.py
- da/kzg_rs/kzg.py
- da/kzg_rs/poly.py
- da/kzg_rs/trusted_setup.py
- da/test_kzg.py
- requirements.txt
This is the easiest workig version of kzg we could came up with.
Commitment + Proof + Verification
Almost everything implemented from scratch for easier understanding.
No reed solomon involved which will be introduced later on in a different PR
> KZG core functionality

- cryptarchia/cryptarchia.py
- cryptarchia/test_common.py
- cryptarchia/test_fork_choice.py
- cryptarchia/test_leader.py
- cryptarchia/test_ledger_state_update.py
Currently the epoch stabilization schedule is only set in tests, we've defined the spec to allow any schedule when instantiated. This PR mostly updates the tests to reflect the new schedule:
The epoch stabilization schedule controls the order that epoch state data is stabilized and the duration of each stabilization period.
Previously ouroborous followed a 4 3 3 schedule (4k/f, 3k/f, 3k/f slots).
the first 4k/f + 3k/f = 7k/f slots were a buffer between when the stake distribution snapshot was taken and when the nonce snapshot is taken. The intention is to have a wide enough gap to prevent any adversary from having being able to influence the next epoch's nonce through coin grinding.
The move to 3 3 4 schedule means we have a gap of 6k/f slots between when the stake distribution snapshot …
> cryptarchia: Update epoch stabilization schedule to 334 (from 433)

- da/common.py
- da/encoder.py
- da/kzg_rs/kzg.py
- da/kzg_rs/rs.py
- da/test_dispersal.py
- da/test_encoder.py
We use field elements of size 32 bytes, but not every arbitrary 32 bytes can be encoded as field points in the bls381 curve. For that we can only chunk up to 31 bytes which are then extended to 32 bytes elements.
> DA: Encode arbitrary data

- cryptarchia/cryptarchia.py
- cryptarchia/test_ledger_state_update.py
It seems that we should find the position of the "parent" of the block to be added when trying to create a fork, but the current implementation finds the position of the "block" to be added.
Please correct me if I'm wrong.
> cryptarchia: fix try_create_fork to find parent block

- da/test_verifier.py
- da/verifier.py
Verifiers should know what was already attested, and if it was already attested just skip next same blobs verification attempts.
> DA: Verifier skip duplicated blobs intents

- da/api/test_flow.py
- da/test_full_flow.py
Couple tests to demonstrate storing of the same blob with different indexes.
> Da api ext tests

- da/api/common.py
- da/api/test_flow.py
- da/common.py
- da/test_full_flow.py
DA Api main methods definition and tests using Nomos DA Protocol.
The latest revision focuses only on `read` and `write` methods and provides `MockBlobStore` to demonstrate a naive way of indexing blobs for a specific `app_id`.
Two new definitions were added to the overall DA spec:
- VID - verifiable information dispersal structure, which is written into a block after attestations for an original data dispersal are verified by block producer.
- VID holds two fields: `cert_id` and `metadata`
- `cert_id` is derived from `aggregated_column_commitment` and `rows_commitments` using [_build_attestation_message](https://github.com/logos-co/nomos-specs/blob/b1e13f79c5e4ddefbd8424a3188bc093c355d234/da/dispersal.py#L73)
- `metadata` is received together with the actual dispersal certificate from EZ …
> DA Api Tests

- cryptarchia/cryptarchia.py
- cryptarchia/test_common.py
- cryptarchia/test_fork_choice.py
- cryptarchia/test_leader.py
- cryptarchia/test_ledger_state_update.py
- cryptarchia/test_orphaned_proofs.py
- cryptarchia/test_stake_relativization.py
The main thrust of this PR is implementing Stake Relativization, but in doing so, a few issues with the orphan handling and fork management code came up and so this PR has gotten a bit more complex with the various fixes.
Unfortunately the bugs were revealed after I had done the majority of the stake relativization implementation otherwise I would have split them out into smaller PR's.
notable bugs:
- orphans from complex branching structures failed to validate
- we would lose track of the current branch on re-org
I've updated the specification in Notion from learnings having gone through the implementation process, namely the inference period is no longer the entire epoch, we need a stable value for total stake for when we enter the next epoch: …
> Stake Relativization Specification + Fixes

- da/encoder.py
We were using modulus over sha256 which may lead to duplicates. Using 31bytes len blake2b is safer.
> DA: Use blake2b for 31 bytes digests

- da/test_verifier.py
- da/verifier.py
Targets `update-v1` [PR](https://github.com/logos-co/nomos-specs/pull/117), removes mentions about attestations, simplifies the verifier function with a comment about the implementer responsibility to make verification idempotent.
> NomosDA update v1 verifier

- da/api/common.py
- da/api/test_flow.py
- da/common.py
- da/dispersal.py
- da/encoder.py
- da/test_dispersal.py
- da/test_encoder.py
- da/test_full_flow.py
- da/test_verifier.py
- da/verifier.py
Modify and rename hash_commitment method. Now we just hash the column commitment itself.
> NomosDA spec v1 updates

- .github/workflows/ci.yml
Recently, the `actions/setup-python@v5` has started installing Python 3.13 instead of 3.12. Ideally our code should work with 3.13, but installing dependencies is failing.
The first error is:
```
../scipy/meson.build:159:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake
```
https://github.com/logos-co/nomos-specs/actions/runs/13521718813/job/37782294686#step:4:103
This can be resolved by upgrading `scipy` to the latest (1.15.2). I tested it in my local.
However, I got another error when installing [`poseidon-hash==0.1.4`](https://github.com/logos-co/nomos-specs/blob/5c64a0bd11b4e0ef9d896297e14735f1f8a530cd/requirements.txt#L14).
```
Collecting numba<0.60,>=0.55 (from galois~=0.3.6->poseidon-hash==0.1.4->-r requirements.txt (line 14))
...
RuntimeError: Cannot install on …
```
> build: pin python to 3.12 (not 3.13) due to outdated dependencies

- cryptarchia/cryptarchia.py
- cryptarchia/test_fork_choice.py
Add Boostrapping and Online modes to cryptarchia, including relevant tests. The Boostrap mode uses the Genesis fc rule, while Online uses Praos. Swtitching between the two rules is left to the implementation and is specified in the public Notion as linked in the comment
> Add Boostrapping/Online modes

- da/assignations/refill.py
- da/assignations/test_refill.py
Implemented state aware subnetworks filling algorithm.
The algorithm works as follows:
1. Remove nodes that are not active from the previous subnetworks assignations
2. Get all active nodes ordered by, primary the number of subnetworks each participant is at and secondary by the `DeclarationId` of the participant (ascending order).
3. Get all subnetworks ordered by the number of participants in each subnetwork
4. Until all subnetworks are filled up to replication factor and all nodes are assigned:
1. Select the subnetwork with the least participants
2. Select the participant with less participation
3. Add the participant into the subnetwork and increment its participation count
4. Add the participant and the subnetwork into the respective collections and reorder them based on ordering …
> feat: Implement subnetworks assignations algorithm
